// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "commonStatus.h"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



_init_in_def_( const ::CORBA::Short commonStatus::ANGLE_UPPER_LIMIT_ERROR = 1; )

_init_in_def_( const ::CORBA::Short commonStatus::ANGLE_LOWER_LIMIT_ERROR = 2; )

_init_in_def_( const ::CORBA::Short commonStatus::INVERSE_KINEMA_ERROR = 3; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_VALUE_LENGTH_ERROR = 16; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_1_VALUE_LENGTH_ERROR = 17; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_2_VALUE_LENGTH_ERROR = 18; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_3_VALUE_LENGTH_ERROR = 19; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_4_VALUE_LENGTH_ERROR = 20; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_5_VALUE_LENGTH_ERROR = 21; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_6_VALUE_LENGTH_ERROR = 22; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_7_VALUE_LENGTH_ERROR = 23; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_8_VALUE_LENGTH_ERROR = 24; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_9_VALUE_LENGTH_ERROR = 25; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_10_VALUE_LENGTH_ERROR = 26; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_11_VALUE_LENGTH_ERROR = 27; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_12_VALUE_LENGTH_ERROR = 28; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_13_VALUE_LENGTH_ERROR = 29; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_14_VALUE_LENGTH_ERROR = 30; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_15_VALUE_LENGTH_ERROR = 31; )

_init_in_def_( const ::CORBA::Short commonStatus::IN_KIND_ERROR = 4096; )

_init_in_def_( const ::CORBA::Short commonStatus::OUT_KIND_ERROR = 4097; )

_init_in_def_( const ::CORBA::Short commonStatus::JOINT_NUM_ERROR = 4098; )

_init_in_def_( const ::CORBA::Short commonStatus::PART_NUM_ERROR = 4099; )

_init_in_def_( const ::CORBA::Short commonStatus::PLUGIN_NAME_ERROR = 4100; )

_init_in_def_( const ::CORBA::Short commonStatus::KIND_ERROR = 8192; )

_init_in_def_( const ::CORBA::Short commonStatus::VALUE_ZERO_ERROR = 8193; )

_init_in_def_( const ::CORBA::Short commonStatus::MISSMATCH_ERROR = 8194; )

_init_in_def_( const ::CORBA::Short commonStatus::INI_JOINT_ERROR = 8195; )

_init_in_def_( const ::CORBA::Short commonStatus::VALUE_JOINT_ERROR = 8196; )

_init_in_def_( const ::CORBA::Short commonStatus::FIRST_TIME_ERROR = 8197; )

_init_in_def_( const ::CORBA::Short commonStatus::OTHER_MOTION_ERROR = 8198; )

_init_in_def_( const ::CORBA::Short commonStatus::TIME_CHANGE_WARNING = 8199; )

_init_in_def_( const ::CORBA::Short commonStatus::FIRST_POINT_ERROR = 8200; )

_init_in_def_( const ::CORBA::Short commonStatus::FALL_ON_JOINT_ERROR = 8201; )

_init_in_def_( const ::CORBA::Short commonStatus::SPEED_ZERO_ERROR = 8202; )

_init_in_def_( const ::CORBA::Short commonStatus::PROTECTIVE_STOP_ERROR = 8203; )

_init_in_def_( const ::CORBA::Short commonStatus::UNJUST_VALUE_ERROR = 8204; )

_init_in_def_( const ::CORBA::Short commonStatus::SERVO_STATUS_ERROR = 12288; )

_init_in_def_( const ::CORBA::Short commonStatus::NO_CONTENTS_SEQ_ERROR = 12289; )

_init_in_def_( const ::CORBA::Short commonStatus::SAME_JOINT_SEQ_ERROR = 12290; )

_init_in_def_( const ::CORBA::Short commonStatus::NOT_SPECIFIED_JOINT_ERROR = 12291; )

_init_in_def_( const ::CORBA::Short commonStatus::UNKNOWN_JOINT_ERROR = 12292; )

_init_in_def_( const ::CORBA::Short commonStatus::INPUT_ANGLE_ERROR = 12293; )

_init_in_def_( const ::CORBA::Short commonStatus::CALIB_ANGLE_ERROR = 12294; )

_init_in_def_( const ::CORBA::Short commonStatus::RE_CALIBRATION = 12295; )

_init_in_def_( const ::CORBA::Short commonStatus::EMERGENCY_ERROR = 12296; )

_init_in_def_( const ::CORBA::Short commonStatus::CHECK_SENSOR_ERROR = 12298; )

_init_in_def_( const ::CORBA::Short commonStatus::MOVE_FOR_ZPOS_ERROR = 12299; )

_init_in_def_( const ::CORBA::Short commonStatus::CALIBRATION_ERROR = 12300; )

_init_in_def_( const ::CORBA::Short commonStatus::SERVO_ON_ERROR = 12301; )

_init_in_def_( const ::CORBA::Short commonStatus::GET_MC_ERROR = 12302; )

_init_in_def_( const ::CORBA::Short commonStatus::CALIBRATION_ZPOS_ERROR = 12303; )

_init_in_def_( const ::CORBA::Short commonStatus::INPUT_MARK_ANGLE_UP_ERROR = 12545; )

_init_in_def_( const ::CORBA::Short commonStatus::INPUT_MARK_ANGLE_DOWN_ERROR = 12546; )

_init_in_def_( const ::CORBA::Short commonStatus::CHANGE_CURRENT_ERROR = 12547; )

_init_in_def_( const ::CORBA::Short commonStatus::SET_ROTATION_ERROR = 12548; )

_init_in_def_( const ::CORBA::Short commonStatus::WRITE_CALIB_PARAM_ERROR = 12549; )

_init_in_def_( const ::CORBA::Short commonStatus::INPUT_ROT_ERROR = 12550; )

_init_in_def_( const ::CORBA::Short commonStatus::NULL_SEQ_ERROR = 12551; )

_init_in_def_( const ::CORBA::Short commonStatus::SIGN_OF_ANGLE_ERROR = 12552; )

_init_in_def_( const ::CORBA::Short commonStatus::TARGET_JOINT_ERROR = 12553; )

_init_in_def_( const ::CORBA::Short commonStatus::GET_LIMIT_ERROR = 12560; )

_init_in_def_( const ::CORBA::Short commonStatus::LIMIT_MOVE_ERROR = 12561; )

_init_in_def_( const ::CORBA::Short commonStatus::HARD_LIMIT_ERROR = 12562; )

_init_in_def_( const ::CORBA::Short commonStatus::READ_PARAM_FILE_ERROR = 12563; )

_init_in_def_( const ::CORBA::Short commonStatus::STATE_PAUSE_ERROR = 12800; )

_init_in_def_( const ::CORBA::Short commonStatus::STATE_ALARM_ERROR = 13056; )

_init_in_def_( const ::CORBA::Short commonStatus::NO_MOVE_ERROR = 13312; )

_init_in_def_( const ::CORBA::Short commonStatus::GET_PARTIAL_MC_ERROR = 13568; )

_init_in_def_( const ::CORBA::Short commonStatus::EXECUTION_ERROR = 13824; )

_init_in_def_( const ::CORBA::Short commonStatus::MOVE_TO_CALIB_SERVO_ERROR = 16385; )

_init_in_def_( const ::CORBA::Short commonStatus::MOVE_TO_CALIB_ERROR = 20481; )

_init_in_def_( const ::CORBA::Short commonStatus::TRAVEL_ERROR = 24577; )

_init_in_def_( const ::CORBA::Short commonStatus::DO_MIX = 28673; )

_init_in_def_( const ::CORBA::Short commonStatus::STOP_MIX = 28674; )

_init_in_def_( const ::CORBA::Short commonStatus::ADD_MOSION_LIST_LAST = 28675; )

_init_in_def_( const ::CORBA::Short commonStatus::STOP_MOSION_LIST = 28676; )

_init_in_def_( const ::CORBA::Short commonStatus::CALL_DEL_COMMAND = 28677; )

_init_in_def_( const ::CORBA::Short commonStatus::CALL_ADD_COMMAND = 28678; )

_init_in_def_( const ::CORBA::Short commonStatus::CALL_STOP_COMMAND = 28679; )

_init_in_def_( const ::CORBA::Short commonStatus::STOP_MOTION = 28680; )

_init_in_def_( const ::CORBA::Short commonStatus::SIGN_OF_WAIT_LENGTH_ERROR = 28681; )

_init_in_def_( const ::CORBA::Short commonStatus::MOTION_LIST_OVER_ERROR = 28682; )

