#!/usr/bin/env python
# Switch controller service
# Switches the Nextage from the default botharms controller to rarm/larm controllers

from controller_manager_msgs.srv import SwitchController
import rospy

service_name = "/controller_manager/switch_controller"
rospy.wait_for_service(service_name)

try:
    switch_controller = rospy.ServiceProxy(service_name, SwitchController)

    # Enforce a strict change between controllers
    ret = switch_controller(['larm_controller', 'rarm_controller'], 
                            ['botharms_controller'], 2, True, 0)

except rospy.ServiceException as e:
    print("Controller switch failed: %s" %e)